### ISSUE TITLE
Use Custom Folders and Use Custom Names not working 

### ISSUE THREAD

**Issue by SaroGFX** [demersdesigns/sketch-batch-create-symbols#22]
Sketch Version 55.2 
No errors

![PinkCluelessHyena-size_restricted](https://user-images.githubusercontent.com/3781800/60960309-117e4880-a30a-11e9-921f-1a442efcfd1d.gif)

**Comment by demersdesigns** [comment]
Thanks for taking the time to report this issue! I'll take a look and see what I can find.

**Comment by demersdesigns** [comment]
This should be fixed with the 2.0 release. Please give it a try and let me know!
